### ISSUE TITLE
[Suggestion] Add Linux Support

### ISSUE THREAD

**Issue by zxp19821005** [johan-perso/agendapp#2]
As titled.
I've shifted the package to ArchLinux AUR : https://aur.archlinux.org/packages/agendapp
Before 1.2.0, it can build successful and run well,I just modify this:
```
sed "s|-exe|-linux|g;s|win32|linux|g;s|icon.ico|icon.png|g;s|release-builds|dist|g" -i package.json
```
But on 1.3.0, I've got errors:
```
==> 获取源代码...
  -> 正在升级 agendapp-1.3.0 git 仓库...
  -> 找到 agendapp.sh
==> 正在验证 source 文件，使用sha256sums...
    agendapp-1.3.0 ... 已跳过
    agendapp.sh ... 通过
==> 正在释放源码...
  -> 正在建立 agendapp-1.3.0 git 仓库的拷贝...
重置分支 'makepkg'
==> 正在删除现存的 $pkgdir/ 目录...
==> 正在开始 build()...
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for appdmg@0.6.6: wanted {"os":"darwin"} (current: {"os":"linux"})
npm ERR! notsup Valid os:  darwin
npm ERR! notsup Actual os: linux
```

**Comment by zxp19821005** [comment]
Here is the log run on ArchLinux:
```
$ electron20 ./app 
Mica-Electron only works on Windows!
Mica-Electron: Disabled
Settings path: /home/zxp-endeavouros/.config/Agendapp/config.json
[785309:1120/184830.269440:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[785309:1120/184830.269476:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
Showing at start...
Showing window...
Window showed.
Applying blur effet.
Checking updates...
IPC used config: get settings undefined
IPC used config: get agenda undefined
Update available! We got 1.2.0 and the latest is 1.3.0.
Window lost focus, hiding...
IPC used config: get settings undefined
IPC used config: get agenda undefined
Showing window...
Window showed.
Window lost focus, hiding...
Stopping app...
```
Maybe just Mica-Electron can't work.
And another suggestion:
Will you please set the default language to English and add another language support such as Chinese[zh-CN]?
![2023-11-20_18-52](https://github.com/johan-perso/agendapp/assets/4915850/18ef563b-95ff-4f58-be0d-4df02f025b85)

**Comment by johan-perso** [comment]
Hi! Thanks for the work, the incoming update (in 2-3 weeks) will include an official support for Linux with some fixes, while based on v1.3.0. Thanks for the tip and the suggestions! I will try to add translation in the app for English language, but Chinese will not be integrated by myself, it would be mindful if you add it yourself with a PR when the update is ready.

I keep this issue opened until the update is officially released.

**Comment by johan-perso** [comment]
Hi! I have finished the update. You can check the last changelog in the GitHub Releases and re-open this issue if you have anything to tell me about.

**Comment by zxp19821005** [comment]
It's OK now,thank you!
